use_frameworks!

target 'DMColorManager_Example' do
  pod 'DMColorManager', :path => '../'

  target 'DMColorManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
